compile: src/CLexer.cpp src/COperation.cpp src/CNumber.cpp src/main.cpp
	g++ -o savelmyk src/CLexer.cpp src/COperation.cpp src/CNumber.cpp src/main.cpp -Isrc

all:
	echo "Not ready"

run:
	echo "Not ready"

clean:
	rm src/*.o savelmyk

doc:
	echo "Not rady"

test:
	cd examples && ./test.sh

