compile: src/CLexer.cpp src/COperation.cpp src/CNumber.cpp src/CAdmin.cpp src/main.cpp src/testgen.cpp
	g++ -o testgen src/testgen.cpp
	g++ -o savelmyk src/CLexer.cpp src/COperation.cpp src/CNumber.cpp src/CAdmin.cpp src/main.cpp -Isrc

all:
	echo "Not ready"

run:
	echo "Not ready"

clean:
	rm -f src/*.o savelmyk testgen

doc:
	echo "Not rady"

test:
	cd examples && ./test.sh

